const pitchArtists = [
  "ANNA",
  "Aurora Halal",
  "Ben Rau",
  "Ben UFO",
  "The Black Madonna",
  "Carista",
  "Cassettes For Kids",
  "Collarbones",
  "Cooper Saver",
  "Curses",
  "DJ BORING",
  "DJ Nobu",
  "Fantastic Man",
  "Fjaak",
  "Fleetmac Wood",
  "Folamour",
  "Hiatus Kaiyote",
  "Hunee",
  "Jennifer Cardini",
  "Job Jobse",
  "Jordan Brando",
  "Kllo",
  "Kobosil",
  "Late Nite Tuff Guy",
  "Maceo Plex",
  "Marcel Dettmann",
  "Memphis LK",
  "Midland",
  "Moopie",
  "Nathan Micay",
  "Nina Kraviz",
  "Objekt",
  "Papa Smurf",
  "Peter Van Hoesen",
  "Project Pablo",
  "Regis",
  "Richie Hawtin",
  "Robert Hood",
  "Shubostar",
  "Skatebård",
  "Skin On Skin",
  "Sleep D",
  "SPFDJ",
  "Stephan Bodzin",
  "Telephones",
  "TERR",
  "Tijana T",
  "Whiskey Houston"
]